# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
    frontend-server-container:
        image: frontend-server
        build:
            context: .
        environment:
            NODE_ENV: production
        env_file: .env
        ports:
            - 3010:3010
